language: "pt"
questionnaire_language: "en"
title: SAVE THE INTERNET NA EUROPA
action: Junte-se a nós e participe na ação! Envie uma mensagem à sua entidade reguladora
keywords:
  -	neutralidade da Internet
  -	Internet aberta
  -	serviços específicos
  -	gestão de tráfego
  -	vias rápidas pagas
  -	"taxa zero"
  -	Europa
  -	Mercado único de telecomunicações
  -	neutralidade da Internet
  -	neutralidade da Internet
  -	neutralidade da Internet
  -	Günther Oettinger
  -	Internet
  -	Open internet
  -	Specialized services
  -	Traffic management
  -	BEREC
  -	vias rápidas pagas
  -	"taxa zero"
  -	Europa
  -	EU
  -	Mercado único de telecomunicações
  -	RTR-GmbH
  -	Institut Belge des Postes et Télécommunications, IBPT / BIPT
  -	Communications Regulation Commission, CRC
  -	Croatian Post and Electronic Communications Agency, HAKOM
  -	Office of the Commissioner of Telecommunications and Postal Regulation, OCECPR
  -	Czech Telecommunication Office, CTU
  -	Danish Business Authority, DBA
  -	Estonian Competition Authority, ECA
  -	Finnish Communications Regulatory Authority, FICORA
  -	Autorité de Régulation des Communications électroniques et des Postes, ARCEP
  -	Federal Network Agency, BNetzA
  -	Hellenic Telecommunications and Post Commission, EETT
  -	National Media and Infocommunications Authority, NMHH
  -	Commission for Communications Regulation, COMREG
  -	Autorità per le Garanzie nelle Comunicazioni, AGCOM
  -	Public Ultilities Commission, SPRK
  -	Communications Regulatory Authority, RRT
  -	Institut Luxembourgeois de Régulation, ILR
  -	Malta Communications Authority, MCA
  -	Office of Electronic Communications, UKE
  -	Autoridade Nacional de Comunicações, ANACOM
  -	National Authority for Management and Regulation in Communications, ANCOM
  -	Telecommunications Regulatory Authority of the Slovak Republic, TU SR
  -	Post and Electronic Communications Agency, APEK
  -	Comisión Nacional de los Mercados y la Competencia
  -	National Post and Telecommunications Agency, PTS
  -	Authority for Consumers and Markets, ACM
  -	Office of Communications, OFCOM
  -	European Commission, EC
  -	Austria
  -	Belgium
  -	Bulgaria
  -	Croatia
  -	CYPRUS
  -	CZECH REPUBLIC
  -	DENMARK
  -	ESTONIA
  -	FINLAND
  -	FRANCE
  -	GERMANY
  -	GREECE
  -	HUNGARY
  -	IRELAND
  -	ITALY
  -	LATVIA
  -	LITHUANIA
  -	LUXEMBOURG
  -	MALTA
  -	POLAND
  -	PORTUGAL
  -	ROMANIA
  -	SLOVAK REPUBLIC
  -	SLOVENIA
  -	SPAIN
  -	SWEDEN
  -	THE NETHERLANDS
  -	UNITED KINGDOM
